[package]
name = "umbrella"
description = "Cross network client to write data into blockchain."
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
ferris-says = "0.1"
structopt = "0.2.18"
stderrlog="0.4.1"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }
hex = "0.3"
bch="0.1.1"
secp256k1 = "0.11"
rust-base58 = "0.0.4"
linked-hash-map = "0.5"
ring = "0.14"
base32="0.4.0"
bech32="0.7.1"

[patch.crates-io]
#bch = {path= '../rust-bch/'}
bch = {git = 'https://github.com/flyingw/rust-bch.git'}

[profile.release]
opt-level = "s" # prefer size
lto = true      # shrink binary
