[package]
name = "didactic-umbrella"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
ferris-says = "0.1"
structopt = "0.2.18"
stderrlog="0.4.1"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }
bch="0.1.1"

[patch.crates-io]
#bch = {path= '../rust-bch/'}
bch = {git = 'https://github.com/flyingw/rust-bch.git'}
